print("Welcome")
file1 = open("myfile.txt", "w") 
file1.write("Pratyush jain \nKamal jain \n12200769\nLucknow\n")
file1.close()
file1 = open("myfile.txt", "a")
file1.write("Archana jain \n")
file1.close()
file1=open("myfile.txt","r")
print(file1.read())
print("byebye")